### ISSUE TITLE
Error on Hugo 0.20 and after-dark 1.4.0

### ISSUE THREAD

**Issue by DanielChesters** [comfusion/after-dark#28] opened 2017-04-10 20:21 UTC
Hi,

Since I have update after-dark source and hugo, I have error on hugo server and hugo generation page : 

```
[daniel@zoidberg source]$ LANG=C hugo version
Hugo Static Site Generator v0.20 linux/amd64 BuildDate: 2017-04-10T20:39:26+02:00
[daniel@zoidberg source]$ LANG=C hugo
WARNING: Site config's rssURI is deprecated and will be removed in a future release. Set baseName in outputFormats.RSS.
Started building sites ...
ERROR 2017/04/10 22:19:04 Error while rendering "home": template: /home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/index.html:35:7: executing "/home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/index.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
[daniel@zoidberg source]$ LANG=C hugo server
WARNING: Site config's rssURI is deprecated and will be removed in a future release. Set baseName in outputFormats.RSS.
Started building sites ...
ERROR 2017/04/10 22:19:11 Error while rendering "taxonomyTerm": template: /home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/_default/terms.html:35:7: executing "/home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/_default/terms.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/10 22:19:11 Error while rendering "home": template: /home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/index.html:35:7: executing "/home/daniel/data/Documents/Developpement/blog/source/themes/after-dark/layouts/index.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
Built site for language en:
0 of 1 draft rendered
0 future content
0 expired content
0 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 6 ms
Watching for changes in /home/daniel/data/Documents/Developpement/blog/source/{data,content,layouts,static,themes}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by smp** [comment] 2017-04-11 04:30
+1 - having the same issue.

**Comment by jhabdas** [comment] 2017-04-11 04:52
Sorry about the issue guys. The issue is occurring as a result of the [Custom Output Formats](https://gohugo.io/extras/output-formats/) introduced in Hugo `v0.20`. Specifically, because (see note at bottom of page linked):

<q>Hugo will look for the name given, so you can name it whatever you want. But if you want it treated as plain text, you should use the file suffix and, if needed, the name of the Output Format (<code>[partial name].[OutputFormat].[suffix]</code>).</q>

When I named the critical files `css.html` I did so with the intention of changing them to `.css` once Hugo supported mixed templates. Here's your chance to help make it happen:

https://github.com/spf13/hugo/issues/3273 (please upvote now)

Meanwhile, your options are to override the base template and partials, and rename the partials to exclude the `css` `OutputFormat`. Or sit on Hugo `0.19` for a few days while I work out a proper solution.

**Comment by jhabdas** [comment] 2017-04-16 14:16
Support for Hugo 0.20.2 (release coming soon) added in `after-dark@1.5.0`. Please let me know if you need any help upgrading by responding to this issue after I close it. Please [see the CHANGELOG](https://github.com/comfusion/after-dark/blob/master/CHANGELOG.md#150-2017-04-16) for a list of what new.

**Closed by jhabdas** 2017-04-16 14:16 UTC
